### PR TITLE
Update ChangeLog.md

### PR DESCRIPTION
**Pull request by sannant**

### CODE REVIEW

**Review by pastewka — APPROVED** [review]

**Comment by sannant** [comment]
I checked the timeout is 45 minutes for the tests. I o not know why the tests got cancelled after 2 minutes

**Comment by pastewka** [comment]
It gets cancelled when one of the other test fails, which seems to be the case.

**Comment by pastewka** [comment]
It gets cancelled when one of the other test fails, which seems to be the case.

**Comment by sannant** [comment]
Ah I clicked on the wrong one... 

Seems that netCDF can't find numpy during installation.

**Pull request merged**
